# Generated by Django 5.0.1 on 2024-01-18 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_data', '0005_delete_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_data.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
