# Generated by Django 5.0.1 on 2024-01-17 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0002_employee_reporting_to'),
        ('office_data', '0003_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office_data.designation'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
