# Generated by Django 5.0.1 on 2024-01-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0003_remove_designation_employee_employee_role_and_more'),
        ('office_data', '0003_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='office_data.designation'),
        ),
    ]
