# Generated by Django 5.0.1 on 2024-01-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
