# Generated by Django 5.0.1 on 2024-01-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0009_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
    ]
